export const KAREN_TYPES = {
    manager: {
        id: 'manager',
        name: 'Manager Karen',
        health: 100,
        speed: 2.0,
        scoreValue: 100,
        detectionRange: 15,
        aggressionRange: 8,
        confrontationDistance: 4,
        detectionAngle: Math.PI * 0.7,
        dialogue: [
            "I know the owner!",
            "Are you recording me?!",
            "This is unacceptable!",
            "I want to speak to your supervisor!",
            "Do you know who I am?!",
            "I have been waiting here for FOUR MINUTES!",
        ],
        hitReactions: [
            "OW! My highlight!",
            "You can't do this!",
            "I'm calling corporate!",
            "My husband is a lawyer!",
            "Do you have ANY idea who I am?!",
        ],
        visual: {
            bodyType: 'average',
            skinTone: 0xd4a574,
            outfitColor: 0x1a1a2e,
            shoeColor: 0x111111,
            hairStyle: 'asymmetricBob',
            hairColor: 0xd6b66f,
            accessories: ['phone', 'handbag'],
        },
    },
    hoa: {
        id: 'hoa',
        name: 'HOA President Karen',
        health: 120,
        speed: 1.8,
        scoreValue: 150,
        detectionRange: 18,
        aggressionRange: 10,
        confrontationDistance: 5,
        detectionAngle: Math.PI * 0.8,
        dialogue: [
            "Your grass is above regulation height!",
            "That color is NOT approved!",
            "I have documented this violation!",
            "This neighborhood has STANDARDS!",
            "Let me check my clipboard...",
            "Section 4, paragraph 2 of the bylaws!",
        ],
        hitReactions: [
            "This is a violation!",
            "I'm adding this to the record!",
            "You'll be hearing from the board!",
            "That's going on your permanent file!",
            "The HOA will NOT stand for this!",
        ],
        visual: {
            bodyType: 'average',
            skinTone: 0xd4a574,
            outfitColor: 0x4a7c59,
            shoeColor: 0x888877,
            hairStyle: 'brunetteBob',
            hairColor: 0x8b6914,
            accessories: ['clipboard', 'visor', 'measuringTape'],
        },
    },
    retail_return: {
        id: 'retail_return',
        name: 'Retail Return Karen',
        health: 110,
        speed: 1.9,
        scoreValue: 150,
        detectionRange: 14,
        aggressionRange: 7,
        confrontationDistance: 4,
        detectionAngle: Math.PI * 0.6,
        dialogue: [
            "I don't need a receipt for this!",
            "It's defective!",
            "Your return policy is ridiculous!",
            "I want to speak to a manager!",
            "I'm a loyal customer!",
            "This store is always like this!",
        ],
        hitReactions: [
            "That's assault!",
            "I'm filing a complaint!",
            "My lawyer will hear about this!",
            "I'm never shopping here again!",
            "You'll regret this!",
        ],
        visual: {
            bodyType: 'curvy',
            skinTone: 0xd4a574,
            outfitColor: 0xcc6644,
            shoeColor: 0xaa8866,
            hairStyle: 'auburnBob',
            hairColor: 0x8b3a2a,
            accessories: ['shoppingBag', 'productBox', 'purse'],
        },
    },
};

export const KAREN_BASE = {
    health: 100,
    speed: 2,
    detectionRange: 15,
    aggressionRange: 10,
    dialogueInterval: 4000,
    hitStunDuration: 800,
    ragdollDuration: 2000,
    colliderRadius: 0.4,
    colliderHeight: 1.6,
};
