export const WEAPON_DEFS = {
    croc: {
        id: 'croc',
        displayName: 'Croc',
        projectileModel: 'croc',
        velocity: 22,
        gravity: -15,
        mass: 0.4,
        radius: 0.25,
        drag: 0.01,
        bounce: 0.4,
        maxBounces: 3,
        cooldown: 600,
        ammo: Infinity,
        spread: 0.02,
        baseDamage: 25,
        rotationSpeed: 8,
        impactEffect: 'thud',
        statusEffect: null,
        statusDuration: 0,
        scoreModifier: 1.0,
        viewColor: 0x2d5a27,
        viewScale: [0.35, 0.12, 0.18],
    },
    waterBalloon: {
        id: 'waterBalloon',
        displayName: 'Water Balloon',
        projectileModel: 'waterBalloon',
        velocity: 28,
        gravity: -18,
        mass: 0.6,
        radius: 0.4,
        drag: 0.02,
        bounce: 0.05,
        maxBounces: 1,
        cooldown: 900,
        ammo: 12,
        spread: 0.03,
        baseDamage: 10,
        rotationSpeed: 3,
        impactEffect: 'splash',
        splashRadius: 2.5,
        statusEffect: 'soaked',
        statusDuration: 6,
        scoreModifier: 0.8,
        viewColor: 0x4488ff,
        viewScale: [0.2, 0.2, 0.2],
    },
    gardenGnome: {
        id: 'gardenGnome',
        displayName: 'Garden Gnome',
        projectileModel: 'gardenGnome',
        velocity: 14,
        gravity: -12,
        mass: 1.2,
        radius: 0.35,
        drag: 0.005,
        bounce: 0.15,
        maxBounces: 1,
        cooldown: 1500,
        ammo: 5,
        spread: 0.01,
        baseDamage: 45,
        rotationSpeed: 4,
        impactEffect: 'ceramic',
        tags: ['lawn_ornament'],
        statusEffect: null,
        statusDuration: 0,
        scoreModifier: 1.5,
        viewColor: 0xdd4444,
        viewScale: [0.25, 0.4, 0.25],
    },
};

export const PROJECTILE_MODELS = {
    croc: {
        color: 0x2d5a27,
        emissive: 0x1a3a18,
        scale: [0.35, 0.12, 0.18],
    },
    waterBalloon: {
        color: 0x4488ff,
        emissive: 0x2244aa,
        scale: [0.25, 0.25, 0.25],
    },
    gardenGnome: {
        color: 0xdd4444,
        emissive: 0x882222,
        scale: [0.25, 0.4, 0.25],
    },
};

export const STATUS_DEFS = {
    soaked: {
        id: 'soaked',
        name: 'SOAKED',
        duration: 6,
        modifiers: {
            speedMultiplier: 0.7,
            specialCooldownMultiplier: 1.5,
        },
    },
    cited: {
        id: 'cited',
        name: 'CITED',
        duration: 5,
        modifiers: {
            speedMultiplier: 0.8,
        },
    },
    escalated: {
        id: 'escalated',
        name: 'ESCALATED',
        duration: 4,
        modifiers: {
            speedMultiplier: 0.75,
        },
    },
    returned: {
        id: 'returned',
        name: 'RETURNED',
        duration: 3,
        modifiers: {},
    },
};
