export const KAREN_TYPES = {
    manager: {
        id: 'manager',
        name: 'Manager Karen',
        health: 100,
        speed: 2.0,
        scoreValue: 100,
        color: 0xd4a574,
        outfitColor: 0x222222,
        hairColor: 0xc8a864,
        detectionRange: 15,
        aggressionRange: 8,
        confrontationDistance: 4,
        detectionAngle: Math.PI * 0.7,
        specialAbilityInterval: 10000,
        specialAbility: 'call_the_manager',
        dialogue: [
            "I know the owner!",
            "Are you recording me?!",
            "This is unacceptable!",
            "I want to speak to your supervisor!",
            "Do you know who I am?!",
            "I have been waiting here for FOUR MINUTES!",
        ],
        hitReactions: [
            "OW! My highlight!",
            "You can't do this!",
            "I'm calling corporate!",
            "My husband is a lawyer!",
            "Do you have ANY idea who I am?!",
        ],
        height: 1.65,
    },
    hoa: {
        id: 'hoa',
        name: 'HOA President Karen',
        health: 120,
        speed: 1.8,
        scoreValue: 150,
        color: 0xd4a574,
        outfitColor: 0x4a7c59,
        hairColor: 0xd4b878,
        detectionRange: 18,
        aggressionRange: 10,
        confrontationDistance: 5,
        detectionAngle: Math.PI * 0.8,
        specialAbilityInterval: 12000,
        specialAbility: 'violation_notice',
        dialogue: [
            "Your grass is above regulation height!",
            "That color is NOT approved!",
            "I have documented this violation!",
            "This neighborhood has STANDARDS!",
            "Let me check my clipboard...",
            "Section 4, paragraph 2 of the bylaws!",
        ],
        hitReactions: [
            "This is a violation!",
            "I'm adding this to the record!",
            "You'll be hearing from the board!",
            "That's going on your permanent file!",
            "The HOA will NOT stand for this!",
        ],
        height: 1.68,
    },
};

export const KAREN_BASE = {
    health: 100,
    speed: 2,
    detectionRange: 15,
    aggressionRange: 10,
    dialogueInterval: 4000,
    hitStunDuration: 800,
    ragdollDuration: 2000,
    colliderRadius: 0.4,
    colliderHeight: 1.6,
};
